import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "UIForge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-screen overflow-hidden">
          <div>
            <Sidebar />
          </div>
          <div className="h-full w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
